#!/usr/bin/env python3
"""
Claw Multi-Model Automation System
Integrated pipeline for research, content, code, and sales
"""

import json
import os
import sys
from datetime import datetime
from pathlib import Path

class ModelRouter:
    """Routes tasks to optimal models based on use case"""
    
    def __init__(self, config_path="model_router.json"):
        with open(config_path, 'r') as f:
            self.config = json.load(f)
    
    def get_model(self, task_type, prefer_speed=False):
        """Get optimal model for task type"""
        task_config = self.config['models'].get(task_type, self.config['models']['research'])
        
        if prefer_speed:
            return task_config['fallback']
        return task_config['primary']
    
    def get_params(self, task_type):
        """Get generation parameters for task type"""
        task_config = self.config['models'].get(task_type, self.config['models']['research'])
        return {
            'max_tokens': task_config['max_tokens'],
            'temperature': task_config['temperature']
        }

class ResearchPipeline:
    """Research and report generation pipeline"""
    
    def __init__(self, router):
        self.router = router
        self.output_dir = Path("research_output")
        self.output_dir.mkdir(exist_ok=True)
    
    def research_topic(self, query, depth="medium"):
        """Research a topic and generate structured report"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"research_{query.replace(' ', '_')[:30]}_{timestamp}.md"
        filepath = self.output_dir / filename
        
        report = f"""# Research Report: {query}

**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M")}
**Depth:** {depth}
**Model:** {self.router.get_model('research')}

## Summary

[This is a placeholder. The actual research would be generated by calling the Ollama Cloud API with the research model.]

## Key Findings

1. Finding 1...
2. Finding 2...
3. Finding 3...

## Sources

- Source 1
- Source 2

## Next Steps

- Action item 1
- Action item 2

---
*Generated by Claw Research Pipeline*
"""
        
        filepath.write_text(report, encoding='utf-8')
        return str(filepath)

class ContentEngine:
    """Social media and YouTube content generation"""
    
    def __init__(self, router):
        self.router = router
        self.output_dir = Path("content_output")
        self.output_dir.mkdir(exist_ok=True)
    
    def generate_x_thread(self, topic, num_tweets=5):
        """Generate X/Twitter thread"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"x_thread_{topic.replace(' ', '_')[:20]}_{timestamp}.md"
        filepath = self.output_dir / filename
        
        content = f"""# X Thread: {topic}

**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M")}
**Model:** {self.router.get_model('content')}

## Thread

"""
        for i in range(1, num_tweets + 1):
            content += f"""### Tweet {i}/{num_tweets}

[Tweet content would be generated here using the content model]

---

"""
        
        content += "\n*Generated by Claw Content Engine*\n"
        filepath.write_text(content, encoding='utf-8')
        return str(filepath)
    
    def generate_youtube_script(self, topic, duration_minutes=10):
        """Generate YouTube video script"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"yt_script_{topic.replace(' ', '_')[:20]}_{timestamp}.md"
        filepath = self.output_dir / filename
        
        script = f"""# YouTube Script: {topic}

**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M")}
**Target Duration:** {duration_minutes} minutes
**Model:** {self.router.get_model('content')}

## Hook (0:00-0:30)

[Hook would be generated here]

## Introduction (0:30-1:30)

[Introduction content]

## Main Content

### Section 1

### Section 2

### Section 3

## Call to Action

## Outro

---
*Generated by Claw Content Engine*
"""
        
        filepath.write_text(script, encoding='utf-8')
        return str(filepath)

class CodeGenerator:
    """Website and application generator"""
    
    def __init__(self, router):
        self.router = router
        self.output_dir = Path("code_output")
        self.output_dir.mkdir(exist_ok=True)
    
    def generate_website(self, name, description, features=None):
        """Generate full website template"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        project_dir = self.output_dir / f"{name.replace(' ', '_').lower()}_{timestamp}"
        project_dir.mkdir(exist_ok=True)
        
        # Create structure
        (project_dir / "index.html").write_text(f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{name}</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header>
        <h1>{name}</h1>
        <p>{description}</p>
    </header>
    <main>
        <section id="hero">
            <h2>Welcome</h2>
            <p>[Content generated by code model]</p>
        </section>
    </main>
    <script src="app.js"></script>
</body>
</html>
""", encoding='utf-8')
        
        (project_dir / "styles.css").write_text("""/* Styles generated by Claw Code Generator */

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: system-ui, -apple-system, sans-serif;
    line-height: 1.6;
    color: #333;
}

header {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
    padding: 2rem;
    text-align: center;
}

main {
    max-width: 1200px;
    margin: 0 auto;
    padding: 2rem;
}
""", encoding='utf-8')
        
        (project_dir / "app.js").write_text("""// JavaScript generated by Claw Code Generator

document.addEventListener('DOMContentLoaded', () => {
    console.log('App initialized');
});
""", encoding='utf-8')
        
        (project_dir / "README.md").write_text(f"""# {name}

{description}

## Generated by Claw Code Generator
**Model:** {self.router.get_model('code')}
**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M")}

## Structure

- `index.html` - Main HTML file
- `styles.css` - CSS styles
- `app.js` - JavaScript functionality

## Usage

Open `index.html` in a browser or deploy to any static hosting.
""", encoding='utf-8')
        
        return str(project_dir)
    
    def generate_app(self, name, description, platform="python"):
        """Generate small application"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        project_dir = self.output_dir / f"{name.replace(' ', '_').lower()}_{timestamp}"
        project_dir.mkdir(exist_ok=True)
        
        if platform == "python":
            (project_dir / "main.py").write_text(f"""#!/usr/bin/env python3
\"\"\"
{name}
{description}

Generated by Claw Code Generator
Model: {self.router.get_model('code')}
Date: {datetime.now().strftime("%Y-%m-%d %H:%M")}
\"\"\"

def main():
    print(f"Welcome to {name}!")
    # TODO: Implement functionality
    pass

if __name__ == "__main__":
    main()
""", encoding='utf-8')
            
            (project_dir / "requirements.txt").write_text("""# Dependencies generated by Claw Code Generator
# Add your dependencies here
""", encoding='utf-8')
        
        return str(project_dir)

class SalesSystem:
    """Service sales and proposal generator"""
    
    def __init__(self, router):
        self.router = router
        self.output_dir = Path("sales_output")
        self.output_dir.mkdir(exist_ok=True)
    
    def generate_service_offer(self, service_name, target_audience, price_range):
        """Generate service offer template"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"offer_{service_name.replace(' ', '_')[:20]}_{timestamp}.md"
        filepath = self.output_dir / filename
        
        offer = f"""# Service Offer: {service_name}

**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M")}
**Target:** {target_audience}
**Price Range:** {price_range}
**Model:** {self.router.get_model('sales')}

## Headline

[Compelling headline would be generated here]

## Problem

[Problem statement]

## Solution

[Your solution]

## Features & Benefits

1. Feature 1 - Benefit
2. Feature 2 - Benefit
3. Feature 3 - Benefit

## Pricing

{price_range}

## Call to Action

[Strong CTA]

## Guarantee

[Risk reversal]

---
*Generated by Claw Sales System*
"""
        
        filepath.write_text(offer, encoding='utf-8')
        return str(filepath)
    
    def generate_proposal(self, client_name, project_description, deliverables):
        """Generate client proposal"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"proposal_{client_name.replace(' ', '_')[:15]}_{timestamp}.md"
        filepath = self.output_dir / filename
        
        proposal = f"""# Project Proposal

**Client:** {client_name}
**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M")}
**Model:** {self.router.get_model('sales')}

## Executive Summary

[Brief overview of the project]

## Project Description

{project_description}

## Deliverables

"""
        for i, item in enumerate(deliverables, 1):
            proposal += f"{i}. {item}\n"
        
        proposal += """
## Timeline

- Week 1: [Phase 1]
- Week 2: [Phase 2]
- Week 3: [Phase 3]

## Investment

[Pricing details]

## Next Steps

1. [Step 1]
2. [Step 2]
3. [Step 3]

---
*Generated by Claw Sales System*
"""
        
        filepath.write_text(proposal, encoding='utf-8')
        return str(filepath)

class ClawSystem:
    """Unified automation system"""
    
    def __init__(self):
        self.router = ModelRouter()
        self.research = ResearchPipeline(self.router)
        self.content = ContentEngine(self.router)
        self.code = CodeGenerator(self.router)
        self.sales = SalesSystem(self.router)
    
    def run_research(self, query, depth="medium"):
        """Run research pipeline"""
        print(f"🔍 Researching: {query}")
        filepath = self.research.research_topic(query, depth)
        print(f"✅ Report saved to: {filepath}")
        return filepath
    
    def run_content_x(self, topic, num_tweets=5):
        """Generate X thread"""
        print(f"📝 Generating X thread: {topic}")
        filepath = self.content.generate_x_thread(topic, num_tweets)
        print(f"✅ Thread saved to: {filepath}")
        return filepath
    
    def run_content_youtube(self, topic, duration=10):
        """Generate YouTube script"""
        print(f"🎬 Generating YouTube script: {topic}")
        filepath = self.content.generate_youtube_script(topic, duration)
        print(f"✅ Script saved to: {filepath}")
        return filepath
    
    def run_website(self, name, description, features=None):
        """Generate website"""
        print(f"🌐 Generating website: {name}")
        filepath = self.code.generate_website(name, description, features)
        print(f"✅ Website saved to: {filepath}")
        return filepath
    
    def run_app(self, name, description, platform="python"):
        """Generate application"""
        print(f"💻 Generating {platform} app: {name}")
        filepath = self.code.generate_app(name, description, platform)
        print(f"✅ App saved to: {filepath}")
        return filepath
    
    def run_sales_offer(self, service_name, target_audience, price_range):
        """Generate service offer"""
        print(f"💰 Generating service offer: {service_name}")
        filepath = self.sales.generate_service_offer(service_name, target_audience, price_range)
        print(f"✅ Offer saved to: {filepath}")
        return filepath
    
    def run_sales_proposal(self, client_name, project_description, deliverables):
        """Generate client proposal"""
        print(f"📄 Generating proposal for: {client_name}")
        filepath = self.sales.generate_proposal(client_name, project_description, deliverables)
        print(f"✅ Proposal saved to: {filepath}")
        return filepath
    
    def help(self):
        """Show usage help"""
        return """
Claw Multi-Model Automation System

USAGE:
    python claw_system.py <command> [args...]

COMMANDS:
    research <query> [depth]       - Research topic and generate report
    content-x <topic> [tweets]     - Generate X/Twitter thread
    content-yt <topic> [minutes]   - Generate YouTube script
    website <name> <description>   - Generate website template
    app <name> <description> [lang]- Generate application
    sales-offer <service> <audience> <price>
                                   - Generate service offer
    sales-proposal <client> <description> [deliverables...]
                                   - Generate client proposal
    help                           - Show this help

EXAMPLES:
    python claw_system.py research "AI agentic commerce trends"
    python claw_system.py content-x "Why ETH beats BTC as treasury" 7
    python claw_system.py content-yt "Building automated income streams" 15
    python claw_system.py website "My Agency" "Digital marketing services"
    python claw_system.py app "TaskTracker" "Simple todo app" python
    python claw_system.py sales-offer "X Growth Service" "Crypto founders" "$500-2000/month"
    python claw_system.py sales-proposal "ACME Corp" "Marketing automation setup" "Strategy doc" "Implementation" "Training"

MODELS:
    Research: gemma4:31b-cloud
    Content: llama3.3:cloud
    Code: qwen3-coder:480b-cloud
    Sales: mistral:7b-cloud
"""

def main():
    # Fix Windows encoding
    import sys
    if sys.platform == 'win32':
        sys.stdout.reconfigure(encoding='utf-8')
    
    system = ClawSystem()
    
    if len(sys.argv) < 2:
        print(system.help())
        return
    
    command = sys.argv[1]
    args = sys.argv[2:]
    
    try:
        if command == "research":
            if len(args) < 1:
                print("Usage: research <query> [depth]")
                return
            query = args[0]
            depth = args[1] if len(args) > 1 else "medium"
            system.run_research(query, depth)
        
        elif command == "content-x":
            if len(args) < 1:
                print("Usage: content-x <topic> [tweets]")
                return
            topic = args[0]
            num_tweets = int(args[1]) if len(args) > 1 else 5
            system.run_content_x(topic, num_tweets)
        
        elif command == "content-yt":
            if len(args) < 1:
                print("Usage: content-yt <topic> [minutes]")
                return
            topic = args[0]
            duration = int(args[1]) if len(args) > 1 else 10
            system.run_content_youtube(topic, duration)
        
        elif command == "website":
            if len(args) < 2:
                print("Usage: website <name> <description>")
                return
            name = args[0]
            description = args[1]
            features = args[2:] if len(args) > 2 else None
            system.run_website(name, description, features)
        
        elif command == "app":
            if len(args) < 2:
                print("Usage: app <name> <description> [platform]")
                return
            name = args[0]
            description = args[1]
            platform = args[2] if len(args) > 2 else "python"
            system.run_app(name, description, platform)
        
        elif command == "sales-offer":
            if len(args) < 3:
                print("Usage: sales-offer <service_name> <target_audience> <price_range>")
                return
            service_name = args[0]
            target_audience = args[1]
            price_range = args[2]
            system.run_sales_offer(service_name, target_audience, price_range)
        
        elif command == "sales-proposal":
            if len(args) < 2:
                print("Usage: sales-proposal <client_name> <project_description> [deliverables...]")
                return
            client_name = args[0]
            project_description = args[1]
            deliverables = args[2:] if len(args) > 2 else ["Initial setup", "Implementation", "Training"]
            system.run_sales_proposal(client_name, project_description, deliverables)
        
        elif command in ["help", "-h", "--help"]:
            print(system.help())
        
        else:
            print(f"Unknown command: {command}")
            print(system.help())
    
    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    main()
